# Generated by Django 5.1.3 on 2024-11-28 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='statua',
            new_name='status',
        ),
        migrations.AddField(
            model_name='recipes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
