# Generated by Django 5.1.3 on 2024-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_statua_recipes_status_recipes_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
